"""Models package."""

from .database import (
    init_database,
    get_db,
    SettingsDB,
    PIARegionsDB,
    TailscaleDevicesDB,
    DeviceRoutingDB,
    ConnectionLogDB,
)
from .schemas import (
    PIACredentials,
    TailscaleAPIKey,
    RegionSelect,
    PIARegion,
    PIARegionList,
    TailscaleDevice,
    TailscaleDeviceList,
    DeviceRoutingToggle,
    PIAStatus,
    TailscaleStatus,
    SystemHealth,
    ConnectionLogEntry,
    ConnectionLogList,
    SuccessResponse,
    ErrorResponse,
)

__all__ = [
    "init_database",
    "get_db",
    "SettingsDB",
    "PIARegionsDB",
    "TailscaleDevicesDB",
    "DeviceRoutingDB",
    "ConnectionLogDB",
    "PIACredentials",
    "TailscaleAPIKey",
    "RegionSelect",
    "PIARegion",
    "PIARegionList",
    "TailscaleDevice",
    "TailscaleDeviceList",
    "DeviceRoutingToggle",
    "PIAStatus",
    "TailscaleStatus",
    "SystemHealth",
    "ConnectionLogEntry",
    "ConnectionLogList",
    "SuccessResponse",
    "ErrorResponse",
]
